<settings>
  <servers>
    <server>
      <id>github</id>
      <username>premrasapalli</username>
      <password>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</password>
    </server>
  </servers>
</settings>
